In [2]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

df = pd.read_csv("/users/raunakchhabra/54339-104884-bundle-archive/HAM10000_metadata.csv")

In [3]:
df

lesion_id      image_id     dx dx_type   age     sex localization
0      HAM_0000118  ISIC_0027419    bkl   histo  80.0    male        scalp
1      HAM_0000118  ISIC_0025030    bkl   histo  80.0    male        scalp
2      HAM_0002730  ISIC_0026769    bkl   histo  80.0    male        scalp
3      HAM_0002730  ISIC_0025661    bkl   histo  80.0    male        scalp
4      HAM_0001466  ISIC_0031633    bkl   histo  75.0    male          ear
...            ...           ...    ...     ...   ...     ...          ...
10010  HAM_0002867  ISIC_0033084  akiec   histo  40.0    male      abdomen
10011  HAM_0002867  ISIC_0033550  akiec   histo  40.0    male      abdomen
10012  HAM_0002867  ISIC_0033536  akiec   histo  40.0    male      abdomen
10013  HAM_0000239  ISIC_0032854  akiec   histo  80.0    male         face
10014  HAM_0003521  ISIC_0032258    mel   histo  70.0  female         back

[10015 rows x 7 columns]

In [4]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()

df['sex']= label_encoder.fit_transform(df['sex'])

df['dx']= label_encoder.fit_transform(df['dx'])

df['dx_type']= label_encoder.fit_transform(df['dx_type'])

df['localization']= label_encoder.fit_transform(df['localization'])

In [5]:
df

lesion_id      image_id  dx  dx_type   age  sex  localization
0      HAM_0000118  ISIC_0027419   2        3  80.0    1            11
1      HAM_0000118  ISIC_0025030   2        3  80.0    1            11
2      HAM_0002730  ISIC_0026769   2        3  80.0    1            11
3      HAM_0002730  ISIC_0025661   2        3  80.0    1            11
4      HAM_0001466  ISIC_0031633   2        3  75.0    1             4
...            ...           ...  ..      ...   ...  ...           ...
10010  HAM_0002867  ISIC_0033084   0        3  40.0    1             0
10011  HAM_0002867  ISIC_0033550   0        3  40.0    1             0
10012  HAM_0002867  ISIC_0033536   0        3  40.0    1             0
10013  HAM_0000239  ISIC_0032854   0        3  80.0    1             5
10014  HAM_0003521  ISIC_0032258   4        3  70.0    0             2

[10015 rows x 7 columns]

In [6]:
df = df.drop(['lesion_id','image_id'],axis=1)

In [7]:
df

dx  dx_type   age  sex  localization
0       2        3  80.0    1            11
1       2        3  80.0    1            11
2       2        3  80.0    1            11
3       2        3  80.0    1            11
4       2        3  75.0    1             4
...    ..      ...   ...  ...           ...
10010   0        3  40.0    1             0
10011   0        3  40.0    1             0
10012   0        3  40.0    1             0
10013   0        3  80.0    1             5
10014   4        3  70.0    0             2

[10015 rows x 5 columns]

In [8]:
df = df.dropna()

In [9]:
x = df.drop('dx',axis=1)
y = df['dx']

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn = KNeighborsClassifier(n_neighbors=5)

In [16]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
pred = knn.predict(x_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
print(confusion_matrix(y_test,pred))

[[  20   11   26    0   13   10    0]
 [   4   41   33    0   36   24    0]
 [  15   36  113    3   38   50    1]
 [   2    1    8    9    6   10    0]
 [  11   44   57    0   68  101    0]
 [  13   55   68    5   65 1454    6]
 [   0    2   14    5    1    8    3]]


In [20]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.31      0.25      0.28        80
           1       0.22      0.30      0.25       138
           2       0.35      0.44      0.39       256
           3       0.41      0.25      0.31        36
           4       0.30      0.24      0.27       281
           5       0.88      0.87      0.88      1666
           6       0.30      0.09      0.14        33

    accuracy                           0.69      2490
   macro avg       0.39      0.35      0.36      2490
weighted avg       0.69      0.69      0.69      2490

